sudo: false
cache:
  yarn: true
  directories:
    - node_modules
language: node_js
node_js:
  - stable
after_script:
  - yarn coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js