sudo: false
osx_image: xcode8.3
cache:
  yarn: true
  directories:
    - node_modules
language: node_js
node_js:
  - stable
before_script:
  - yarn add prepack
after_script:
  - yarn coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js