version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: ./node_modules/codecov/bin/codecov -f coverage/*
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage
workflows:
    build-and-test:
      jobs:
        - build-and-test